Gh 870 conditional none handling
gchq/gaffer-tools pull request #871
Opened 2021-02-12 12:44 UTC by j8934893

2021-04-08 17:31 UTC, t92549 requested changes

2021-04-08 17:31 UTC, t92549 commented on python-shell/src/gafferpy/gaffer_operations.py
>                  self.predicate = JsonConverter.from_json(predicate,
Indentation

2021-04-08 17:31 UTC, t92549 commented on python-shell/src/gafferpy/gaffer_operations.py
>                  self.transform = JsonConverter.from_json(transform, Operation)
Indentation

2021-04-12 11:31 UTC, t92549 commented
Happy to merge after small indentation fixes. Closes #870

2021-04-28 15:56 UTC, n3101 commented
@j8934893 Hiya, we're looking to do a release in a couple of weeks. If you make the requested changes here soonish, we can include this item.

2021-05-21 12:35 UTC, j8934893 commented
Git appears to have done something odd with my local branch so split this into a new PR - https://github.com/gchq/gaffer-tools/pull/897

Sorry for being a pain.

2021-05-21 13:02 UTC, t92549 commented
Closing as superseded by #898

2021-05-21 13:02 UTC, closed without merging